name: Daily Discord Forum Summary

on:
  schedule:
    # Runs hourly at 5 minutes past the hour (adjust minute as needed)
    # See https://crontab.guru/ for cron syntax help
    - cron: '5 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run summarizer script
        env:
          # IMPORTANT: Add these as GitHub Secrets in your repository settings
          # Settings > Secrets and variables > Actions > New repository secret
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FORUM_CHANNEL_ID: ${{ secrets.FORUM_CHANNEL_ID }}
          BOT_CATEGORY_NAME: ${{ secrets.BOT_CATEGORY_NAME }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          # Add any other secrets needed by your utils.py (e.g., API keys for generate/generate_yt)
          # EXAMPLE_API_KEY: ${{ secrets.EXAMPLE_API_KEY }}
        run: python summarize_to_forum.py
